# Generated by Django 5.1.2 on 2024-11-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment_email_list_post_comment_post_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='major',
            field=models.TextField(default='Mechanical Engineering'),
            preserve_default=False,
        ),
    ]
