# Generated by Django 5.1.2 on 2024-11-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='major',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='posts',
        ),
    ]
